# Generated by Django 3.1.1 on 2020-09-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('user_id', models.IntegerField(default=0)),
                ('is_base_product', models.BooleanField(default=False)),
                ('is_optional_product', models.BooleanField(default=False)),
                ('is_custom_product', models.BooleanField(default=False)),
                ('product_img', models.ImageField(blank=True, upload_to='img/products/')),
                ('desired_amount', models.IntegerField(default=0)),
                ('current_amount', models.IntegerField(default=0)),
                ('lacking_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
